
spring:
  freemarker:
    cache: false
    suffix: .ftlh
    staticClassLocation:
      - com.zhengxl.freemarker.tools.UserStaticTool
      - com.zhengxl.freemarker.tools.AnotherStaticTool
server:
  port: 8080


#    template-loader-path: file:E:/templates/