server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:mysql://123.57.211.17:3306/db2?serverTimezone=UTC
    username: root
    password: imw100pass!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
#  autoconfigure:
#    exclude:
#      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: beans
